### ISSUE TITLE
KeyError: 'python'

### ISSUE THREAD

**Issue by Findus23** [ryantam626/jupyterlab_black#10]
Hi and thanks for writing this useful plugin.

I tried installing it and everything in the installation process goes fine.

But when I try to run the formatter I get the following error:

```text
[E 15:04:01.432 LabApp] Uncaught exception POST /jupyterlab_black/format?1543068241426 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_black/format?1543068241426', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/myusername/.virtualenvs/notebooks/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/myusername/.virtualenvs/notebooks/lib/python3.6/site-packages/jupyterlab_black/handlers.py", line 33, in post
        python = data["python"]
    KeyError: 'python'
```

When I add a `print(data) in the line before, I get the following output:
```python
{'code': 'the_python_code_in_the_cell', 'lineLength': 110}
```

It seems like there should be another attribute that points to the python executable (?).

I am using jupyter (lab) in an virtual env and also have that env configured as the jupyter kernel.

Do you have an idea what could be causing this?

**Comment by Findus23** [comment]
Okay, 
This has solved itself. I should have read the readme more properly as I forgot to configure the `blackPythonBin`. Now everything is working fine.

Maybe you could improve the docs/error message.

**Comment by ryantam626** [comment]
Yeah, the docs is probably not the clearest, will improve, thanks for flagging!

Closing the issue now as it seems to be resolved!
