### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by jingzhehu** [ryantam626/jupyterlab_black#3]
Thanks for making this package available ! But when I tried to install the extension, the following error ensued:

```
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.4 <0.17.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.16.3 <0.17.0 @jupyterlab/notebook
>=0.17.2 <0.18.0        >=0.16.3 <0.17.0 @jupyterlab/terminal
```

**Comment by ryantam626** [comment]
Ah! Your Jupyterlab is very up to date! I am working on bumping the allowed dependencies ranges of the package and testing it now :+1:

**Comment by ryantam626** [comment]
I imagine you installed jupyterlab with conda (conda-forge channel)? I just tested the newly released 0.1.4 version of this extension with that jupyterlab and it now seems to work, can you confirm please :grin: ?

**Comment by jingzhehu** [comment]
Perfect ! Things are woking great now. I installed jupyterlab with plain old `pip`.

**Comment by ryantam626** [comment]
That's good to hear!  :+1:  Closing this issue now
