### ISSUE TITLE
Failed to format and server console output "404 post"

### ISSUE THREAD

**Issue by liurui39660** [ryantam626/jupyterlab_black#7]
### My setup

I'm using the 0.2.0 version of jupyterlab-black with python 3.6.5, jupyter lab 0.33.12 within a virtual environment. The jupyter lab runs on an ubuntu 18.04 server and I access to it via my chrome 68, windows 10 laptop.

### What's wrong

I installed the extension following the instruction in the readme. But no matter I use the keyboard shortcut or the command in the commands panel, the cell won't format and there will be a line output to the server console.

`[W 11:06:18.477 LabApp] 404 POST /jupyterlab_black/format?1534561578476 (192.168.28.224) 2.98ms referer=http://super.lab:8889/lab?`

Where the `192.168.28.224` is the IP address of my laptop, `http://super.lab:8889/lab?` is the address I access the jupyter lab, and this domain is resolved locally by the same server itself.

### Installation process
1. `jupyter labextension install @ryantam626/jupyterlab_black`
1. `pip install https://github.com/ryantam626/jupyterlab_black/archive/master.zip`
1. `jupyter serverextension enable --py jupyterlab_black`
1. `pip install black`
1. `blackPythonBin` set to the path of python of the current virtual environment
1. Paste keyboard shortcut to setting editor
1. Try to format the cell in edit mode - fails with the aforementioned output

**Comment by ryantam626** [comment]
Hmm try installing and enabling the serverextension in your server and install black there and use output of `which black` (on your server) as `blackPythonBin`.

**Comment by liurui39660** [comment]
Sorry for the late reply.

The problem is successfully solved after installing and enabling `serverextension`.

But I think to put the output of `which black` to `blackPythonBin` is not a good idea, since when I run the command, the code won't format and the last character of the line is eaten.
