### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by EricCacciavillani** [ryantam626/jupyterlab_black#9]
Hi I couldn't seem to get your project working. But I am just trying to uninstall it since it is completely breaking my Juypter Lab. I am not well versed in notebook extensions so could tell me a very quick fix to just delete it?

**Comment by ryantam626** [comment]
Sorry to hear that. Could you elaborate what have you tried and what are you seeing at the moment?

Also would be grateful to know how is it not working for you, e.g. did you follow through the installation steps, what other things did you try?

**Comment by EricCacciavillani** [comment]
jupyter serverextension disable nbextensions
jupyter serverextension disable jupyterlab_black
jupyter serverextension disable nbextensions --user
jupyter serverextension disable nbextensions --sys-prefix

I got it working at like 2 or 3 in the morning along with some other work sorry a tad bit groggy currently. But this is what I did to get rid of my error.

**Comment by EricCacciavillani** [comment]
As for trying to install it in the first place, I couldn't see the JuypterLab extension in the GUI that you showed in your nice GIF(I actually really liked that by the way : ) )

**Comment by EricCacciavillani** [comment]
But I think this is the part that I don't quite understand.
"Head over to settings editor, and key in the python interpreter path of that Python3.6+ you have with black installed for blackPythonBin."

I am a tad bit confused since there is multiple option here. More than likely it relates to Extension Manager...because its an extension...but I am just trying to make sure I don't make my JuypterLab break again...

**Comment by ryantam626** [comment]
I think you can leave the `nbextensions` alone - I doubt that's what causing the issue.

Also not really sure which part is confusing you, what I really mean is that you need to:-
1. Make sure you have an environment with black installed.
2. Put in the python binary path for the environment stated in (1) into the settings.

**Comment by EricCacciavillani** [comment]
<img width="1286" alt="screen shot 2018-11-12 at 1 39 03 pm" src="https://user-images.githubusercontent.com/16104771/48368078-b31c9f80-e680-11e8-9696-e7077c05f46a.png">
<img width="407" alt="screen shot 2018-11-12 at 1 40 49 pm" src="https://user-images.githubusercontent.com/16104771/48368096-badc4400-e680-11e8-90c7-545e96946cb7.png">

Also the disable actually did fix my problem but I decided to give it another go since I suprised to hear you answer back so soon.

I do have it installed and I don't see the extension in my settings...

**Comment by EricCacciavillani** [comment]
Also I know that isnt where I am supposed to put that one liner...I just put it down/tried it for my own sanity...I am weird

**Comment by ryantam626** [comment]
Hmm, what's generating the output of the second picture?

Could you show the output of `jupyter labextension list` and `jupyter serverextension list` too?

**Comment by EricCacciavillani** [comment]
<img width="878" alt="screen shot 2018-11-12 at 3 04 19 pm" src="https://user-images.githubusercontent.com/16104771/48372341-4d361500-e68c-11e8-9940-f87bfc9da987.png">

**Comment by EricCacciavillani** [comment]
"X is nbextensions importable?"

**Comment by ryantam626** [comment]
Probably due to the fact that you ran `jupyter serverextension disable nbextensions` :confused: 

You didn't install the labextension, try `jupyter labextension install @ryantam626/jupyterlab_black` if you still want to check if it works for you?

**Comment by EricCacciavillani** [comment]
I am pretty sure I re-enabled it.

The code you gave me did cause a change in my settings. (prompted me). But no visual changes....

**Comment by ryantam626** [comment]
What I meant is that there is no server extension called "nbextensions", by enable/disable it, it would only confuse jupyter, hence the output.

Is there anything in the chrome debug console?

**Comment by EricCacciavillani** [comment]
I also get this error when opening from the anaconda gui as well but I don't know how helpful this is to you. 
`[W 20:42:23.035 LabApp] Error loading server extension jupyter-black
Traceback (most recent call last):
File "/Users/ericcacciavillani/anaconda3/envs/ztdl/lib/python3.6/site-packages/notebook/notebookapp.py", line 1573, in init_server_extensions
mod = importlib.import_module(modulename)
File "/Users/ericcacciavillani/anaconda3/envs/ztdl/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jupyter-black'`

As for the google chrome console. It doesn't look like anything is wrong with it. 

<img width="558" alt="screen shot 2018-11-12 at 8 44 41 pm" src="https://user-images.githubusercontent.com/16104771/48385328-0c55f480-e6bc-11e8-9d44-d6c1f19b05d7.png">

**Comment by ryantam626** [comment]
Okay that's not related, it's trying to import `jupyter-black` which is a different plugin.

Here are a few more checks because I can't really figure out what's wrong remotely, some of these are repeated from before because I think they have changed by now.

Before we begin, source your python environment (I believe you have it named `ztdl`).

1. Run `python --version` in terminal
Am not expecting anything in particular, just show me the output.

2. Run `which python` in terminal
Am not expecting anything in particular, just show me the output.

3. Run `which pip` in terminal
Am not expecting anything in particular, just show me the output.

4. Run `pip freeze | grep jupyter` in terminal
Expecting something like `jupyterlab-black==0.2.0` to be there. Also show me the output.

5. Run `jupyter labextension list` in terminal
Expecting something like `@ryantam626/jupyterlab_black v0.2.2  enabled  OK` to be there. Also show me the output.

6. Run `jupyter serverextension list` in terminal
Expecting something like `jupyterlab_black enabled`. Also show me the output.

7. Inspecting Chrome console
Anything highlighted in red?

**Comment by EricCacciavillani** [comment]
<img width="667" alt="screen shot 2018-11-13 at 10 06 56 am" src="https://user-images.githubusercontent.com/16104771/48422115-f3852780-e72b-11e8-84b1-3747179a5fec.png">

**Comment by EricCacciavillani** [comment]
No nothing in red in the Chrome  console. And thats embarrassing; my bad.

**Comment by ryantam626** [comment]
Oh, it's still missing the labextension :thinking:

Are you sure `jupyter labextension install @ryantam626/jupyterlab_black` ran properly?

**Comment by ryantam626** [comment]
Also, apologies I had a typo for step 6, I meant `jupyter serverextension list` :disappointed:

**Comment by EricCacciavillani** [comment]
Oh it didn't post up I am sorry.

**Comment by EricCacciavillani** [comment]
<img width="878" alt="screen shot 2018-11-12 at 3 04 19 pm" src="https://user-images.githubusercontent.com/16104771/48603212-c317d600-e943-11e8-812b-23d90215465c.png">

**Comment by ryantam626** [comment]
Can you post the output of `jupyter labextension install @ryantam626/jupyterlab_black` please? I am guessing for some reason it's failing for you since it's not installed.

**Comment by EricCacciavillani** [comment]
<img width="581" alt="screen shot 2018-11-16 at 3 00 54 pm" src="https://user-images.githubusercontent.com/16104771/48644418-7c13fa00-e9b0-11e8-9f8e-cae50aeccabf.png">

**Comment by ryantam626** [comment]
That command failed -- the red cross at the beginning of the line indicate the command finished with a non-zero return code, which means you should be looking at the output and figure out what's wrong instead of continuing to the next steps.

In this case, it's exactly as it says, there is a conflicting dependency with your jupyterlab and the plugin. I have released a new version (0.2.3) that should no longer conflict with your jupyterlab version :+1: 

So try the same command again, and it should work!

**Comment by EricCacciavillani** [comment]
Alright, I will give a shot later tonight. I have been buried in work/family matters really appreciate your help so far.

**Comment by EricCacciavillani** [comment]
Your an amazing human being and I appreciate you for dealing with me...
A side note is there any way to have formatted able to apply to the entire notebook with one click...? If not your perfectly fine I don't mind clicking on each. (P.S I am suggesting this to friends.)

**Comment by ryantam626** [comment]
Ah, I did think about that functionality before, the implementation detail wasn't that obvious to me at the time so I went back to other stuff that I was working on, perhaps I will give it a go some other time!

Nice to hear that you are suggesting this to friend :wink: I assume things are working well enough! Am closing this issue for now (re-open this if I misunderstood and it's still broken :+1: )
